baseURL = 'https://example.org/'
languageCode = 'fr-fr'
title = 'Recette'

theme = "hello-friend-ng"

[params]
  author = "Antoine Greuzard"
  description = "Un site de recettes de cuisine."
  disqusShortname = "admin"