baseURL = 'https://example.org/'
languageCode = 'fr-fr'
title = 'Recette'

theme = "hello-friend-ng"

[params]
  author = "Antoine Greuzard"
  description = "Un site de recettes de cuisine."
  disqusShortname = "admin"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "À propos"
    url = "/about/"
    weight = 1

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 2